### ISSUE TITLE
Sub-Application Crash.

### ISSUE THREAD

**Issue by AITYunivers** [PiKeyAr/SDLJoystick#7]
Running a sub-app with a SDL object in both the frame and the sub-app frame, crashes upon closing the sub-app.
[Example MFA](https://github.com/PiKeyAr/SDLJoystick/files/11973135/SDLSubAppCrash.zip)

**Comment by PiKeyAr** [comment]
Doesn't crash for me...

**Comment by PiKeyAr** [comment]
Hi! Here's a test version that should work correctly with sub-applications. Your example seems to work fine with it. Could you test it a bit to confirm if there are any more crashes?
[SDLJoy-165.zip](https://github.com/PiKeyAr/SDLJoystick/files/11983301/SDLJoy-165.zip)

**Comment by AITYunivers** [comment]
That fixed the issue in both my Example MFA and my real project. Thanks!

**Comment by PiKeyAr** [comment]
Thanks for testing. I will make a new release soon.
